### ISSUE TITLE
[BUG] Windows Popup control not centered after updating CommunityToolkit.Maui package to version 6.0.0

### ISSUE THREAD

**Issue by uSafi** [CommunityToolkit/Maui#1432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I recently updated the CommunityToolkit.Maui package from version 5.3.0 to 6.0.0, and now the Popup control is no longer centered on my main page.

Setting HorizontalOptions="Center" wouldn't do anything.
I tried setting the Anchor property on xaml and on code-behind but that wasn't posable.

After some investigation, I found that the issue was caused by setting the FlowDirection property of my main content control (a Grid) to "RightToLeft". When I removed this property or set it to "LeftToRight", the Popup control was centered correctly.
(It's Like the popup being drawing from right to left)

So far it's effect on Windows apps, but not Android, and idk about IOS.

I believe this is a bug in the CommunityToolkit.Maui package 6.0.0, and I would like to report it so that it can be fixed in future releases.

Versions used:

CommunityToolkit.Maui: 6.0.0
Please let me know if you need any further information or clarification.

I hope this helps!

### Expected Behavior

The Expected Behavior should have been the same normal behavior of version 5.3.0. 
that is the Popup show at the center, not shifted to the right side of the screen.

### Steps To Reproduce

- Just create a MAUI project.
- Add the package CommunityToolkit.maui version 6.0.0
- Initialize the .NET MAUI Community Toolkit by adding the below line of code
.UseMauiCommunityToolkit()

the rest is the same in the documentation: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup

Change the FlowDirection="RightToLeft" of the Main Content Control (say a Grid or a VerticalStackLayout) and some Labels or buttons.

run the project.
			

### Link to public reproduction project repository

https://github.com/uSafi/Popup-Issue-on-CommunityToolkit.Maui-version-6.0.0

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS: Windows 10.
It run normally on Android, IDK about IOS.
- .NET MAUI: 6.0.0
```

**Comment by brminnick** [comment]
@uSafi Could you verify this bug against the current main branch?

We merged https://github.com/CommunityToolkit/Maui/pull/1361 yesterday which may fix this.

**Comment by uSafi** [comment]
> @uSafi Could you verify this bug against the current main branch?
> 
> We merged #1361 yesterday which may fix this.

Yes I verified it just now, it's fixed and now it's working as expected, good work guys.

**Comment by uSafi** [comment]
> @uSafi Could you verify this bug against the current main branch?
> 
> We merged #1361 yesterday which may fix this.

I downloaded the current main branch, and verified it just now.

The popup samples in the package work normal as expected even when I set a main layout inside a page to FlowDirection="RightToLeft",

but when I reference the package dll (CommunityToolkit.Maui.dll) directly from my sample project, it still not fixed.

Here's my xaml of the Popup:

<?xml version="1.0" encoding="utf-8" ?>
<toolkit:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Testing_Popups.SimplePopup"
             xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
             HorizontalOptions="Center"
             >
    <VerticalStackLayout FlowDirection="RightToLeft">
        <Label Text="This is a very important message!" />
        <Button Text="Close Popup"
                Clicked="OnButtonClicked" />
    </VerticalStackLayout>
</toolkit:Popup>

The code-behind of my MainPage that call that Popup:
        public async static Task DisplayPopup()
        {
            var popup = new SimplePopup();            
            await App.Current.MainPage.ShowPopupAsync(popup);
        }

Btw: the code in that PR seems about the size of the popup, not it's Initial position!.

**Comment by uSafi** [comment]
If I unset the FlowDirection from the main layout "VerticalStackLayout" and set it to individual controls, the popup will show as expected, see...

    <VerticalStackLayout>
        <Label Text="This is a very important message!" FlowDirection="RightToLeft" />
        <Button Text="Close Popup" FlowDirection="RightToLeft"
                Clicked="OnButtonClicked" />
    </VerticalStackLayout>

**Comment by brminnick** [comment]
<img width="1521" alt="image" src="https://github.com/CommunityToolkit/Maui/assets/13558917/e27ec2d1-fb5d-486e-a893-241894c6203f">

Confirmed

**Comment by cat0363** [comment]
@brminnick , If you specify RightToLeft for FlowDirection, do you expect the following behavior?

https://github.com/CommunityToolkit/Maui/assets/125236133/6a5fc5e5-89cf-4007-92ce-1c027cafc85f

If Start is specified for Popup's HorizontalOptions, which position will the Popup be displayed on, right or left?

**Comment by cat0363** [comment]
@brminnick , Or are you expecting something like the following?

https://github.com/CommunityToolkit/Maui/assets/125236133/91c3d285-d2a0-4755-a90e-7ef06cdac850

If you let me know which pattern it is, I will correct it.

**Comment by brminnick** [comment]
> If you specify RightToLeft for FlowDirection, do you expect the following behavior?

Yes, the behavior in the video is what I would expect

> If Start is specified for Popup's HorizontalOptions, which position will the Popup be displayed on, right or left?

I would assume it'd be displayed on the left for `LeftToRight` and on the right for `RightToLeft`.

**Comment by cat0363** [comment]
@brminnick , Thanks for your reply while I was on vacation.
I would like to create a PR using the pattern below.
https://github.com/CommunityToolkit/Maui/issues/1432#issuecomment-1742283361

**Comment by brminnick** [comment]
That'd be great!

**Comment by cat0363** [comment]
@brminnick , If RightToLeft is specified for FlowDirection of Popup Content, the behavior is the same as below on iOS and Android.
https://github.com/CommunityToolkit/Maui/issues/1432#issuecomment-1742300935

Only Windows has the following behavior due to the modification.
https://github.com/CommunityToolkit/Maui/issues/1432#issuecomment-1742283361

If the behavior on the Windows side is correct, the behavior on the Android and iOS sides must also be corrected. On the other hand, if the behavior after modification is incorrect, you will need to modify the Windows side to match the behavior on the Android and iOS sides.

**Comment by cat0363** [comment]
FYI - Below is the behavior of Android and iOS using the latest version of main.

[Android]

https://github.com/CommunityToolkit/Maui/assets/125236133/57c74eaa-7dfa-4b95-adb8-790e8af69147

[iOS]

https://github.com/CommunityToolkit/Maui/assets/125236133/628aaa45-9f20-4632-8fea-72414069f4a5

If the Popup's Content's FlowDirection is RightToLeft and the Popup's HorizontalOptions is Start, 
the Popup will be displayed on the left. Do I need to fix these too?

**Comment by uSafi** [comment]
> FYI - Below is the behavior of Android and iOS using the latest version of main.
> 
> [Android]
> 
>  Android.Emulator.-.pixel_2_-_api_30_5556.2023-10-03.11-30-45.mp4 
> [iOS]
> 
>  iPhone.14.iOS.16.4.2023-10-03.11-22-10.mp4 
> If the Popup's Content's FlowDirection is RightToLeft and the Popup's HorizontalOptions is Start, the Popup will be displayed on the left. Do I need to fix these too?

Yes please fix it, iOS should be exactly like the behavior of Android in the video, the HorizontalOptions Start should show the Popup to the right when FlowDirection is RightToLeft, and to the left when HorizontalOptions is End also when FlowDirection is RightToLeft.
And Thank you for all your help in this.

**Comment by cat0363** [comment]
@uSafi , Thanks for your comment.
I would like to modify it so that platforms other than Windows can also support FlowDirection.

**Comment by raselldev** [comment]
i have my with current flow
login -> showing popup (center) -> dashboard

and if i logout, current main page is change to login. 
i try to login again with same flow, but popup is not center of device. 


My Code.
```
<ScrollView
    HorizontalOptions="CenterAndExpand"
    VerticalOptions="CenterAndExpand">
....
</ScrollView>
```

First starting app
<img width="302" alt="Screenshot 2023-10-05 at 16 14 45" src="https://github.com/CommunityToolkit/Maui/assets/29136223/12dece7c-cb3b-4600-aef8-adea1a4c6044">

After logout and changing main page to login
<img width="331" alt="Screenshot 2023-10-05 at 16 14 09" src="https://github.com/CommunityToolkit/Maui/assets/29136223/2e8e95b8-0e1c-42c1-b5ec-fd6a11fd4553">

**Comment by cat0363** [comment]
@raselldev , If you do not provide the minimum code to reproduce the issue, I will not know whether the issue is resolved or not.
Your problem sounds like a different problem, since the cause of [this issue](https://github.com/CommunityToolkit/Maui/issues/1432#issue-1920333564) is the FlowDirection of the Popup's Content.
