### ISSUE TITLE
[BUG] Maui Community pop up doesn't work in OnAppearing()

### ISSUE THREAD

**Issue by BrianJSavage** [CommunityToolkit/Maui#992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I used the Maui Community PopUp example to test this issue, after I couldn't get it to work in my new app.

I needed to display a message when a page is first opened, so put the PopUp call in OnAppearing().

It fails there with System.InvalidOperationException: 'Could not locate MauiContext.'

Steps to Reproduce
Create the Popup app as described here: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup
Add a call for the pop as below in OnAppearing()
It works with the OnAppearing call commented out, but not if used.

### Expected Behavior

Call pop up from OnAppearing()

### Steps To Reproduce

Download the repo.
Run with and without  commented out DisplayPopup() in OnAppearing().

protected override void OnAppearing()
{
//DisplayPopup();
}

### Link to public reproduction project repository

https://github.com/BrianJSavage/PopUpTest.git

### Environment

```markdown
- .NET MAUI CommunityToolkit: 4.0
- OS: w11
- .NET MAUI: 17.4.4
Latest versions of everything
```

### Anything else?

Nope

**Comment by bijington** [comment]
This is fixed as part of https://github.com/CommunityToolkit/Maui/pull/934

I don't believe we have released this version yet

**Comment by bijington** [comment]
@BrianJSavage I don't see why we wouldn't release this soon (next week or so) but in the meantime you can probably try using the `OnNavigatedTo` method instead of `OnAppearing`

**Comment by BrianJSavage** [comment]
Thanks I'll try that.

**Comment by dg2k** [comment]
> This is fixed as part of #934
> 
> I don't believe we have released this version yet

I am using version 5.1.0 but the issue is still there. Doe that mean the fix is not part of 5.1.0?

**Comment by pictos** [comment]
@dg2k can you provide a small sample that reproduces the issue?

**Comment by jeff-eats-pubsubs** [comment]
Also encountering this issue overriding OnAppearing() to ShowPopupAsync()
